# Generated by Django 4.1.3 on 2022-12-04 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LibraryHall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=32)),
                ('full_name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Rack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('library_hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.libraryhall')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('authors', models.CharField(max_length=256)),
                ('volume', models.IntegerField()),
                ('path', models.IntegerField()),
                ('isbn', models.IntegerField()),
                ('year', models.DateField()),
                ('shelf', models.IntegerField()),
                ('number', models.IntegerField()),
                ('rack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.rack')),
            ],
        ),
    ]
