# Generated by Django 4.1.3 on 2022-12-04 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='book',
            name='path',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='volume',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
